// webapp/src/app/reports/stats/stats.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { ClientService } from "../../client.service";
import { getCanvasElementById, getColourPalette } from "../../shared/chartjs";
import { Chart } from "chart.js";
import * as moment from "moment";
import { HttpParams } from "@angular/common/http";
import { TopNavService } from "../../topnav.service";
import { Subscription } from "rxjs";
import { AppEventCode, AppService } from "../../app.service";

@Component({
    selector: 'app-stats',
    templateUrl: './stats.component.html',
    styleUrls: ['./stats.component.scss']
})
export class StatsComponent implements OnInit, OnDestroy {

    private charts = {
        decoderBytes: null,
        flowMemUse: null,
        tcpMemuse: null,
        kernelPackets: null,
        kernelDrops: null,
    };

    sensors = [];
    sensorName = "";

    subscriptions = new Subscription();

    constructor(private client: ClientService, private topNav: TopNavService, private appService: AppService) {
    }

    ngOnInit(): void {
        this.refresh();
        this.subscriptions.add(this.subscribeAppEvents());
    }

    ngOnDestroy(): void {
        this.subscriptions.unsubscribe();
        this.destroyCharts();
    }

    private subscribeAppEvents(): Subscription {
        return this.appService.subscribe((event: any) => {
            switch (event.event) {
                case AppEventCode.TIME_RANGE_CHANGED:
                    this.refresh();
                    break;
                case AppEventCode.IDLE:
                    break;
            }
        });
    }

    private destroyCharts(): void {
        for (const chart in this.charts) {
            if (this.charts[chart] != null) {
                this.charts[chart].destroy();
            }
        }
    }

    refresh(): void {
        this.refreshSensors();

        this.destroyCharts();
        this.refreshTcpMemuse();
        this.refreshFlowMemuse();
        this.refreshDecoderPkts();
        this.refreshKernelDrops();
        this.refreshDecoderBytes();
    }

    private refreshSensors(): void {
        this.client.get("/api/1/sensors").subscribe((response) => {
            this.sensors = response.data;
        });
    }

    private getParams(): HttpParams {
        let params = new HttpParams().set("time_range", this.topNav.getTimeRangeAsSeconds());
        if (this.sensorName !== "") {
            params = params.set("sensor_name", this.sensorName);
        }
        return params;
    }

    private refreshDecoderBytes(): void {
        const params = this.getParams().set("field", "stats.decoder.bytes");
        this.client.get("/api/1/stats/agg/deriv", params).subscribe((response) => {
            const labels = [];
            const values = [];
            response.data.forEach((e) => {
                labels.push(moment(e.timestamp).toDate());
                values.push(e.value);
            });
            this.charts.decoderBytes = this.buildChart("chart-decoder-bytes", "Decoder Bytes", labels, values);
        });
    }

    private refreshDecoderPkts(): void {
        const params = this.getParams().set("field", "stats.decoder.pkts");
        this.client.get("/api/1/stats/agg/deriv", params).subscribe((response) => {
            const labels = [];
            const values = [];
            response.data.forEach((e) => {
                labels.push(moment(e.timestamp).toDate());
                values.push(e.value);
            });
            this.charts.kernelPackets = this.buildChart("chart-decoder-packets", "Decoder Packets", labels, values);
        });
    }

    private refreshKernelDrops(): void {
        const params = this.getParams().set("field", "stats.capture.kernel_drops");
        this.client.get("/api/1/stats/agg/deriv", params).subscribe((response) => {
            const labels = [];
            const values = [];
            response.data.forEach((e) => {
                labels.push(moment(e.timestamp).toDate());
                values.push(e.value);
            });
            this.charts.kernelDrops = this.buildChart("chart-kernel-drops", "Kernel Drops", labels, values);
        });
    }

    private refreshTcpMemuse(): void {
        const params = this.getParams().set("field", "stats.tcp.xmemuse");
        this.client.get("/api/1/stats/agg", params).subscribe((response) => {
            const labels = [];
            const values = [];
            response.data.forEach((e) => {
                labels.push(moment(e.timestamp).toDate());
                values.push(e.value);
            });
            this.charts.tcpMemuse = this.buildChart("chart-tcp-memuse", "TCP Memory Usage", labels, values);
        });
    }

    private refreshFlowMemuse(): void {
        const params = this.getParams().set("field", "stats.flow.memuse");
        this.client.get("/api/1/stats/agg", params).subscribe((response) => {
            const labels = [];
            const values = [];
            response.data.forEach((e) => {
                labels.push(moment(e.timestamp).toDate());
                values.push(e.value);
            });
            this.charts.flowMemUse = this.buildChart("chart-flow-memuse", "Flow Memory Usage", labels, values);
        });
    }

    private buildChart(elementId: string, title: string, labels: Date[], values: number[]): Chart<any> {
        const ctx = getCanvasElementById(elementId);
        let min = null;
        if (Math.max(...values) === 0) {
            min = 0;
        }

        const chart = new Chart(ctx, {
            type: "line",
            data: {
                labels: labels,
                datasets: [
                    {
                        data: values,
                        backgroundColor: "rgba(0, 90, 0, 0.3)",
                        borderColor: "rgba(0, 90, 0, 1)",
                        pointRadius: 0,
                        fill: true,
                        borderWidth: 1,
                    }
                ]
            },
            options: {
                interaction: {
                    intersect: false,
                },
                responsive: true,
                maintainAspectRatio: false,
                scales: {
                    x: {
                        type: "time",
                    },
                    y: {
                        min: min,
                    }
                },
                plugins: {
                    title: {
                        text: title,
                        display: true,
                    },
                    legend: {
                        display: false,
                    }
                }
            }
        });
        return chart;
    }
}

<div class="row pt-2">
    <div class="col">
        <form class="form-inline">

            <button type="button" class="btn btn-secondary" (click)="refresh()">
                Refresh
            </button>

            <select *ngIf="sensors" class="form-control ml-2" [(ngModel)]="sensorName"
                    (ngModelChange)="refresh()" name="sensorSelector">
                <option value="">All Sensors</option>
                <option *ngFor="let sensor of sensors" [value]="sensor">
                    {{sensor}}
                </option>
            </select>

        </form>
    </div>
</div>

<div class="row pt-2">
    <div class="col-12">
        <canvas height="200" id="chart-decoder-bytes" style="height: 200px;"></canvas>
    </div>
</div>

<div class="row pt-2">
    <div class="col-12">
        <canvas height="200" id="chart-decoder-packets" style="height: 200px;"></canvas>
    </div>
</div>

<div class="row pt-2">
    <div class="col-12">
        <canvas height="200" id="chart-kernel-drops" style="height: 200px;"></canvas>
    </div>
</div>

<div class="row pt-2">
    <div class="col-12">
        <canvas height="200" id="chart-flow-memuse" style="height: 200px;"></canvas>
    </div>
</div>

<div class="row pt-2">
    <div class="col-12">
        <canvas height="200" id="chart-tcp-memuse" style="height: 200px;"></canvas>
    </div>
</div>

// webapp/src/Stats.tsx
// SPDX-FileCopyrightText: (C) 2023 Jason Ish <jason@codemonkey.net>
//
// SPDX-License-Identifier: MIT

import { createEffect, createSignal, For, JSX, onCleanup } from "solid-js";
import { Top } from "./Top";
import { Button, Col, Container, Row } from "solid-bootstrap";
import { timeRangeAsSeconds } from "./settings";
import { getSensors, statsAgg } from "./api";
import { Chart } from "chart.js";
import { parse_timestamp } from "./datetime";
//import "chartjs-adapter-dayjs-4";
import { useSearchParams } from "@solidjs/router";

interface ChartConfig {
  title: string;
  field: string;
  differential: boolean;
  canvasId: string;
}

const CHARTS: ChartConfig[] = [
  {
    title: "Decoder Bytes",
    field: "stats.decoder.bytes",
    differential: true,
    canvasId: "decoderBytes",
  },
  {
    title: "Decoder Packets",
    field: "stats.decoder.pkts",
    differential: true,
    canvasId: "decoderPackets",
  },
  {
    title: "Kernel Drops",
    field: "stats.capture.kernel_drops",
    differential: true,
    canvasId: "kernelDrops",
  },
  {
    title: "Flow Memory",
    field: "stats.flow.memuse",
    differential: false,
    canvasId: "flowMemuse",
  },
  {
    title: "TCP Memory",
    field: "stats.tcp.memuse",
    differential: false,
    canvasId: "tcpMemuse",
  },
];

export function Stats(): JSX.Element {
  const [sensors, setSensors] = createSignal<string[]>([]);
  const [searchParams, setSearchParams] = useSearchParams<{ sensor: string }>();
  let charts: any[] = [];

  onCleanup(() => {
    destroyAllCharts();
  });

  createEffect(() => {
    loadData(timeRangeAsSeconds(), searchParams.sensor);
  });

  function destroyAllCharts() {
    console.log("Destroying charts...");
    while (charts.length > 0) {
      const chart = charts.pop();
      chart.destroy();
    }
  }

  function loadData(timeRange: undefined | number, sensor: string | undefined) {
    destroyAllCharts();

    getSensors().then((response) => {
      setSensors(response.data);
    });

    console.log("Loading chart...");

    for (const chart of CHARTS) {
      statsAgg(chart.field, chart.differential, timeRange, sensor).then(
        (response) => {
          const labels: any[] = [];
          const values: any[] = [];
          response.data.forEach((e) => {
            labels.push(parse_timestamp(e.timestamp).toDate());
            values.push(e.value);
          });
          const canvas = buildChart(
            chart.canvasId,
            chart.title,
            labels,
            values
          );
          charts.push(canvas);
        }
      );
    }
  }

  return (
    <div>
      <Top />
      <Container fluid>
        <Row class={"mt-2"}>
          <Col sm={1}>
            <Button variant={"secondary"}>Refresh</Button>
          </Col>
          <Col>
            <div class={"row align-items-center"}>
              <label for={"event-type-selector"} class={"col-auto"}>
                Sensor:
              </label>
              <div class={"col-auto"}>
                <select
                  class="form-select"
                  id={"event-type-selector"}
                  onchange={(e) => {
                    setSearchParams({ sensor: e.currentTarget.value });
                    e.currentTarget.blur();
                  }}
                >
                  <option value="" selected={searchParams.sensor == undefined}>
                    All
                  </option>
                  <For each={sensors()}>
                    {(sensor) => {
                      return (
                        <>
                          <option
                            value={sensor}
                            selected={sensor == searchParams.sensor}
                          >
                            {sensor}
                          </option>
                        </>
                      );
                    }}
                  </For>
                </select>
              </div>
            </div>
          </Col>
        </Row>
        <For each={CHARTS}>
          {(chart) => (
            <>
              <Row>
                <Col>
                  <div style={"height: 200px; width: 100%"}>
                    <canvas id={chart.canvasId}></canvas>
                  </div>
                </Col>
              </Row>
            </>
          )}
        </For>
      </Container>
    </div>
  );
}

function buildChart(
  elementId: string,
  title: string,
  labels: Date[],
  values: number[]
): Chart<any> {
  const ctx = (
    document.getElementById(elementId) as HTMLCanvasElement
  ).getContext("2d") as CanvasRenderingContext2D;

  const chart = new Chart(ctx, {
    type: "line",
    data: {
      labels: labels,
      datasets: [
        {
          data: values,
          backgroundColor: "rgba(0, 90, 0, 0.3)",
          borderColor: "rgba(0, 90, 0, 1)",
          pointRadius: 0,
          fill: true,
          borderWidth: 1,
        },
      ],
    },
    options: {
      interaction: {
        intersect: false,
      },
      responsive: true,
      maintainAspectRatio: false,
      scales: {
        x: {
          type: "time",
        },
      },
      plugins: {
        title: {
          text: title,
          display: true,
        },
        legend: {
          display: false,
        },
      },
    },
  });
  return chart;
}
